//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RockPaperScissors.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceFile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceFile() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RockPaperScissors.Resources.ResourceFile", typeof(ResourceFile).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string msgBack {
            get {
                return ResourceManager.GetString("msgBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer chose: {0}.
        /// </summary>
        internal static string msgComputerChose {
            get {
                return ResourceManager.GetString("msgComputerChose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal mode.
        /// </summary>
        internal static string msgNormalMode {
            get {
                return ResourceManager.GetString("msgNormalMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rock Paper Scissors.
        /// </summary>
        internal static string msgRockPaperScissors {
            get {
                return ResourceManager.GetString("msgRockPaperScissors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rock Paper Scissors, The Big Bang Theory.
        /// </summary>
        internal static string msgRockPaperScissorsBBT {
            get {
                return ResourceManager.GetString("msgRockPaperScissorsBBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score Board.
        /// </summary>
        internal static string msgSB {
            get {
                return ResourceManager.GetString("msgSB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Game.
        /// </summary>
        internal static string msgStartGame {
            get {
                return ResourceManager.GetString("msgStartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Big Bang Theory Mode.
        /// </summary>
        internal static string msgTBBTMode {
            get {
                return ResourceManager.GetString("msgTBBTMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Its a tie!.
        /// </summary>
        internal static string msgTie {
            get {
                return ResourceManager.GetString("msgTie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You lost :(.
        /// </summary>
        internal static string msgYouLost {
            get {
                return ResourceManager.GetString("msgYouLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You won!!!.
        /// </summary>
        internal static string msgYouWon {
            get {
                return ResourceManager.GetString("msgYouWon", resourceCulture);
            }
        }
    }
}
